docente/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name="docente"
urlpatterns = [
    path('vistaDocente/', views.docente,name="docentes"),
]

empresas/urls.py
from django.urls import path
from . import views

app_name = 'empresas'
urlpatterns = [
    path('empresas/', views.empresas, name='empresas'),
]

inicio/urls.py
from django.urls import path
from . import views

app_name= 'inicio'
urlpatterns = [
    path('', views.inicio, name='inicio'),
]

practicaEvaDos/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('inicio.urls')),
    path('', include('empresas.urls')),
    path('', include("docente.urls")),
]

inicio/models.py
from django.db import models

# Create your models here.

docente/views.py
from django.shortcuts import render

# Create your views here.

def docente(request):
    return render(request, "docente/docentes.html")

empresas/views.py
from django.shortcuts import render

# Create your views here.

def empresas(request):
    return render(request, 'empresas/empresas.html')

inicio/views.py
from django.shortcuts import render

# Create your views here.

def inicio(request):
    return render(request, 'inicio/inicio.html')

docente/templates/docente/docentes.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<title>{% block title %}Portal Docentes INACAP{% endblock %}</title>
<br><br><br><br><br>
<div style="position: relative; display: inline-block;">
    <img src="{% static 'images/docentes-banner-ppal.jpg'%}" alt="Portal de docentes" style="width: 1920px; height: 450px; filter: brightness(50%);" class="center">
    <div style="position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%); color: white; font-size: 50px; font-weight: bold; text-align: center;">Portal del Docente</div>

    <div class="row" style="background-color: darkgrey;">
        <div class="col">
            <div class="card">
                <div class="card-body" style="background-color: darkgrey;">
                    <h5 class="card-title">Acceso a Intranet</h5>
                    <a href="#" class="btn btn-primary" style="background-color: black;">Ingresar</a>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card">
                <div class="card-body" style="background-color: darkgrey;">
                    <h5 class="card-title">Mail Docente</h5>
                    <a href="#" class="btn btn-primary" style="background-color: black;">Ingresar</a>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card">
                <div class="card-body" style="background-color: darkgrey;">
                    <h5 class="card-title">Juntos Cuidémonos</h5>
                    <a href="#" class="btn btn-primary" style="background-color: transparent; color: black; border-color: black;">Ver más</a>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card">
                <div class="card-body" style="background-color: darkgrey;">
                    <h5 class="card-title">Servicios Tecnológicos</h5>
                    <a href="#" class="btn btn-primary" style="background-color: transparent; color: black; border-color: black;">Revisa aquí</a>
                </div>
            </div>
        </div>
    </div>
</div>


<div style="text-align: center; margin-top: 20px;">
    <div style="max-width: 600px; margin: 0 auto;">
        <h1>Modelo de Desarrollo y Gestión Docente TP</h1>
        <p style="margin-bottom: 0;">Nuestro Modelo Educativo Técnico Profesional se apoya en más de 55 años de trayectoria formando con calidad y excelencia bajo el enfoque pedagógico del Aprender Haciendo. Por esto, hemos trabajado en un Modelo de Desarrollo y Gestión Docente - Técnico Profesional, que permita hacer evidente el aporte que representa tu labor en el aprendizaje de nuestros estudiantes, y que nos permita apoyar el desarrollo de tu trayectoria académica en la Institución, potenciando tus fortalezas y en base a tus intereses.</p>
    </div>

{% endblock %}

empresas/templates/empresas/empresas.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<title>

    {% block title %}Empresas - portal.inacap.cl{% endblock %}
</title>
<style>
    .div-image{
        background-image: url("{% static 'images/2400x715-header-servicios-para-empresas.png' %}");
    }
</style>

<div class="div-image" style="filter: contrast(1.2); height: 25em; background-size: cover;margin-top: 112px; display: flex;position: relative;background-position: center;">
    <div style="background-color: rgb(30, 30, 30, .5); width: 100%; height: 100% ;position: absolute; bottom: 0; display: flex; justify-content: center; align-items: center;">
        <h2 style="color: white; font-size: 48px; font-weight: bold; margin-bottom: 12vh;">Servicios para Empresas</h2>
    </div>
</div>

<div style="height: fit-content; justify-content: space-between; align-items: start;display: flex; width: 100%; padding: 50px calc(135px + (201 * ((100vw - 1536px) / (1920 - 1536)))); flex-direction: column; gap: 15px">
    <div style="display: flex; gap: 5px;">
        <i style="background-color: #cc0000; min-height: 100%; width: 5px;" ></i>
        <h2 style="margin: 0px; line-height: 1;font-weight: bold; font-size: 35px;">Prácticas y Empleabilidad</h2>
    </div>
    <p style="font-size: 14px; font-weight: 400; margin-bottom: 50px;">En Emplea INACAP, empresas y organizaciones podrán acceder a distintos servicios que les permitirán gestionar sus procesos de reclutamiento y atracción de talento, con tecnología y el apoyo de un equipo a lo largo de todo Chile.
    </p>
    <div style="display: flex; flex-wrap: wrap; gap: 15px; width: 100%; justify-content: space-between;">

        <div style="background-color: #222220; height: 310px; width: 610px; border-radius: 15px; display: flex; justify-content: center;">
            <div style="display: flex; height: auto; width: 100%; margin: 1.5em; align-items: center; gap: 20px;">
                <img style="border-radius: 15px;height: 274px; width: 274px;" src="https://portal.inacap.cl/documents/47032/850324/bolsa-de-trabajo.png/d499e8f9-078e-2e0c-dde6-b1ac8c9eaa65?version=1.0&t=1718990450871" alt="">
                <div style="display: flex; justify-content: space-between; flex-direction: column; height: 100%; position: relative;">
                    <div style="display: flex; gap: 10px; margin-top: 10px;">
                        <i style="background-color: #cc0000; min-height: 100%; min-width: 5px;" ></i>
                        <h3 style="color: white; line-height: 1; font-weight: 600; margin: 0px; font-size: 22px;">Bolsa de trabajo INACAP</h3>
                    </div>
                    <a href="#" style="margin-bottom: 20px;bottom: 0;right: 0;position: absolute;padding: 7px 15px;border-radius: 23px;border: 2px solid white;width: fit-content;font-size: 17px;">Ver más<svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor" class="bi bi-chevron-right" viewBox="0 0 16 16">
                        <path fill-rule="evenodd" d="M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708"></path>
                      </svg> </a>
                </div>
            </div>
        </div>


        <div style="background-color: #222220; height: 310px; width: 610px; border-radius: 15px; display: flex; justify-content: center;">
            <div style="display: flex; height: auto; width: 100%; margin: 1.5em; align-items: center; gap: 20px;">
                <img style="border-radius: 15px;height: 274px; width: 274px;" src="https://portal.inacap.cl/documents/47032/850324/Proceso-de-Reclutamiento.jpg/bf7a8d0d-e645-1bdb-59b7-052b76b8c253?version=1.0&t=1718990451676" alt="">
                <div style="display: flex; justify-content: space-between; flex-direction: column; height: 100%; position: relative;">
                    <div style="display: flex; gap: 10px; margin-top: 10px;">
                        <i style="background-color: #cc0000; min-height: 100%; min-width: 5px;" ></i>
                        <h3 style="color: white; line-height: 1; font-weight: 600; margin: 0px; font-size: 22px;">Apoyo en reclutamiento y atracción de talento</h3>
                    </div>
                    <a href="#" style="margin-bottom: 20px;bottom: 0;right: 0;position: absolute;padding: 7px 15px;border-radius: 23px;border: 2px solid white;width: fit-content;font-size: 17px;">Ver más<svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor" class="bi bi-chevron-right" viewBox="0 0 16 16">
                        <path fill-rule="evenodd" d="M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708"></path>
                      </svg> </a>
                </div>
            </div>
        </div>

        <div style="background-color: #222220; height: 310px; width: 610px; border-radius: 15px; display: flex; justify-content: center;">
            <div style="display: flex; height: auto; width: 100%; margin: 1.5em; align-items: center; gap: 20px;">
                <img style="border-radius: 15px;height: 274px; width: 274px;" src="https://portal.inacap.cl/documents/47032/850324/Feria_Laboral_800x800-05.jpg/2e681d60-044c-d3bc-13ee-87279905f4bd?version=1.0&t=1718990451409" alt="">
                <div style="display: flex; justify-content: space-between; flex-direction: column; height: 100%; position: relative;">
                    <div style="display: flex; gap: 10px; margin-top: 10px;">
                        <i style="background-color: #cc0000; min-height: 100%; min-width: 5px;" ></i>
                        <h3 style="color: white; line-height: 1; font-weight: 600; margin: 0px; font-size: 22px;">Feria laboral INACAP-CPC</h3>
                    </div>
                    <a href="#" style="margin-bottom: 20px;bottom: 0;right: 0;position: absolute;padding: 7px 15px;border-radius: 23px;border: 2px solid white;width: fit-content;font-size: 17px;">Ver más<svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor" class="bi bi-chevron-right" viewBox="0 0 16 16">
                        <path fill-rule="evenodd" d="M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708"></path>
                      </svg> </a>
                </div>
            </div>
        </div>

        <div style="background-color: #222220; height: 310px; width: 610px; border-radius: 15px; display: flex; justify-content: center;">
            <div style="display: flex; height: auto; width: 100%; margin: 1.5em; align-items: center; gap: 20px;">
                <img style="border-radius: 15px;height: 274px; width: 274px;" src="https://portal.inacap.cl/documents/47032/850324/Emplea_Futuro-800x800.jpg/c67e7278-be00-edaa-1ce3-907919b38655?version=1.0&t=1718990451151" alt="">
                <div style="display: flex; justify-content: space-between; flex-direction: column; height: 100%; position: relative;">
                    <div style="display: flex; gap: 10px; margin-top: 10px;">
                        <i style="background-color: #cc0000; min-height: 100%; min-width: 5px;" ></i>
                        <h3 style="color: white; line-height: 1; font-weight: 600; margin: 0px; font-size: 22px;">Reconocimiento Empleo Futuro</h3>
                    </div>
                    <a href="#" style="margin-bottom: 20px;bottom: 0;right: 0;position: absolute;padding: 7px 15px;border-radius: 23px;border: 2px solid white;width: fit-content;font-size: 17px;">Ver más<svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor" class="bi bi-chevron-right" viewBox="0 0 16 16">
                        <path fill-rule="evenodd" d="M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708"></path>
                      </svg> </a>
                </div>
            </div>
        </div>



    </div>
    
</div>

{% endblock %}

inicio/templates/inicio/inicio.html
{% extends 'base.html' %}
{% block content %}
<style>
    a{
        color: white;
        text-decoration: none;
        font-weight: bold;
        font-size: 14px;
        gap: 5px;
        display: flex;
        align-items: baseline;
        
    }h3{
      color: white;
      font-size: 18px;
      font-weight: bold;
    }p{
      color: white;
      font-size: 14px;
    }
</style>
<div style="height: 28em; background-image: url(static/images/DestacadoHome-2400x750.jpg); background-size: cover;margin-top: 117px; display: flex;position: relative;background-position:center;">
    <div style="background-color: rgb(30, 30, 30, .9); width: 100%; height: fit-content; position: absolute; bottom: 0; display: flex; justify-content: center; align-items: center;">
      <p style="color: white; margin: 1em 0px; font-size: 17px; font-weight: 400;">Carreras con Sello Tecnológico, alta empleabilidad y alineadas con las necesidades del país</p>
    </div>
    <div style="display: flex; width: 35%; flex-direction: column;padding: 25px 0px 0px 80px;">
      <h2 style="text-shadow: #1E1E1E 1px 4px 1px; ;line-height: 1; color: white;font-size: 45px; font-weight: bold; ">Inicia el periodo Admisión 2025 para estudiantes nuevos: ¡Matricúlate GRATIS!</h2>
      <button style="background-color: white; color: #ce392b; width: fit-content;border: none; padding: 0px; font-size: 30px; font-weight: bold; border-radius: 20px; margin-top: 70px ;">Más Información</button>
    </div>

</div>

<div style="height: 16em; justify-content: center; align-items: center;display: flex; width: 100%;gap: 1vw;">
    <div style="background-color: #690715; border-radius: 15px; height: 169px;width: 392px; padding: 24px;">
      <h3>Centro Formación Técnica (CFT)</h3>
      <p>Carreras cortas, modernas y tecnológicas; con alta empleabilidad y con el Sello del Aprender Haciendo.</p>
      <a href="#" style="text-decoration: underline; font-size: 17px; text-underline-position: under;">Ver más<svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor" class="bi bi-chevron-right" viewBox="0 0 16 16" >
        <path fill-rule="evenodd" d="M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708"/>
      </svg> </a>
    </div>
    <div style="background-color: #a20b1b; border-radius: 15px; height: 169px;width: 392px; padding: 24px;">
      <h3>Instituto Profesional (IP)</h3>
      <p>Desarróllate en los sectores productivos y de servicios con una formación profesional.</p>
      <a href="#" style="text-decoration: underline; font-size: 17px; text-underline-position: under;">Ver más<svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor" class="bi bi-chevron-right" viewBox="0 0 16 16" >
        <path fill-rule="evenodd" d="M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708"/>
      </svg> </a>
    </div>
    <div style="background-color: #f77531; border-radius: 15px; height: 169px;width: 392px; padding: 24px;">
      <h3 style="color: black;" >Educación Continua</h3>
      <p style="margin: 0PX;color: black;">Elige actualizarte y</p>
      <p style="color: black;" >seguir especializándote</p>
      <a  href="#" style="text-decoration: underline; font-size: 17px; text-underline-position: under; color: black;">Ver más<svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor" class="bi bi-chevron-right" viewBox="0 0 16 16" >
        <path fill-rule="evenodd" d="M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708"/>
      </svg> </a>
    </div>
    
</div>


{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}INACAP es Aprender Haciendo - portal.inacap.cl{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="shortcut icon" href="https://portal.inacap.cl/documents/47032/0/favicon.ico/4de91b69-5360-8e06-2306-0e6cf2e2b489?q=0.08923704800448284" type="image/x-icon">
</head>
<body>
    <style>
        a{
            color: white;
            text-decoration: none;
            font-weight: bold;
            font-size: 14px;
            gap: 5px;
            display: flex;
            align-items: baseline;
            
        }
    </style>
    <nav style="background-color: #1E1E1E; height: 7em; color: white; position: fixed; z-index: 1000; width: 100%; top: 0;">
      <div style="display: grid; grid-template-columns: 1fr 3.5fr; height: 100%; width: 100%; padding: 0px calc(135px + (201 * ((100vw - 1536px) / (1920 - 1536))));align-items: center;"> 
            <a style="gap:0px;" href="{% url  'inicio:inicio' %}">
                <img src="{% static  'images/logo-footer.png' %}" height="35px" alt="">
            </a>
            <div style="display: flex; flex-direction: column; height: 100%;">
                <div style="display: flex; justify-content: space-evenly;align-items: center;height: 50%; margin-top: 5px;">     
                    <a href="#">Ed. Media</a>
                    <a href="#">Estudiantes</a>
                    <a href="#">Exalumnos</a>
                    <a href="{% url 'docente:docentes' %}">Docentes</a>
                    <a href="#">Biblioteca</a>
                    <a href="{% url 'empresas:empresas' %}">Empresas</a>
                    <a href="#">Validar Certificados</a>
                    <a href="#">Portal de Pagos <svg style="transform: rotate(180deg);" xmlns="http://www.w3.org/2000/svg" width="6" height="6" fill="currentColor" class="bi bi-triangle-fill" viewBox="0 0 16 16">
                        <path fill-rule="evenodd" d="M7.022 1.566a1.13 1.13 0 0 1 1.96 0l6.857 11.667c.457.778-.092 1.767-.98 1.767H1.144c-.889 0-1.437-.99-.98-1.767z"/>
                      </svg></a>
                    <a href="#">Acceso Intranet <svg style="transform: rotate(180deg);" xmlns="http://www.w3.org/2000/svg" width="6" height="6" fill="currentColor" class="bi bi-triangle-fill" viewBox="0 0 16 16">
                        <path fill-rule="evenodd" d="M7.022 1.566a1.13 1.13 0 0 1 1.96 0l6.857 11.667c.457.778-.092 1.767-.98 1.767H1.144c-.889 0-1.437-.99-.98-1.767z"/>
                      </svg></a>
                    <i class="bi bi-person-arms-up"></i>
                </div>
                <hr style="border-top:  1px solid white; opacity: 1; margin: 0px 0px 5px 0px;">
                <div style="display: flex;justify-content: space-evenly;align-items: center;height: 50%;">
                    <a href="">CFT INACAP  <svg style="transform: rotate(180deg);" xmlns="http://www.w3.org/2000/svg" width="6" height="6" fill="currentColor" class="bi bi-triangle-fill" viewBox="0 0 16 16">
                        <path fill-rule="evenodd" d="M7.022 1.566a1.13 1.13 0 0 1 1.96 0l6.857 11.667c.457.778-.092 1.767-.98 1.767H1.144c-.889 0-1.437-.99-.98-1.767z"/>
                      </svg></a>
                    <a href="">IP INACAP <svg style="transform: rotate(180deg);" xmlns="http://www.w3.org/2000/svg" width="6" height="6" fill="currentColor" class="bi bi-triangle-fill" viewBox="0 0 16 16">
                        <path fill-rule="evenodd" d="M7.022 1.566a1.13 1.13 0 0 1 1.96 0l6.857 11.667c.457.778-.092 1.767-.98 1.767H1.144c-.889 0-1.437-.99-.98-1.767z"/>
                      </svg></a>
                    <a href="">Educación Continua</a>
                    <a href="">Universidad</a>
                    <a href="">Financiamiento <svg style="transform: rotate(180deg);" xmlns="http://www.w3.org/2000/svg" width="6" height="6" fill="currentColor" class="bi bi-triangle-fill" viewBox="0 0 16 16">
                        <path fill-rule="evenodd" d="M7.022 1.566a1.13 1.13 0 0 1 1.96 0l6.857 11.667c.457.778-.092 1.767-.98 1.767H1.144c-.889 0-1.437-.99-.98-1.767z"/>
                      </svg></a>
                    <a href="">Sedes <svg style="transform: rotate(180deg);" xmlns="http://www.w3.org/2000/svg" width="6" height="6" fill="currentColor" class="bi bi-triangle-fill" viewBox="0 0 16 16">
                        <path fill-rule="evenodd" d="M7.022 1.566a1.13 1.13 0 0 1 1.96 0l6.857 11.667c.457.778-.092 1.767-.98 1.767H1.144c-.889 0-1.437-.99-.98-1.767z"/>
                      </svg></a>
                    <a href="">Carreras</a>
                    <a href="">Noticias <svg style="transform: rotate(180deg);" xmlns="http://www.w3.org/2000/svg" width="6" height="6" fill="currentColor" class="bi bi-triangle-fill" viewBox="0 0 16 16">
                        <path fill-rule="evenodd" d="M7.022 1.566a1.13 1.13 0 0 1 1.96 0l6.857 11.667c.457.778-.092 1.767-.98 1.767H1.144c-.889 0-1.437-.99-.98-1.767z"/>
                      </svg></a>
                    <button style="background: white; padding: 5px 20px; border-radius: 20px; font-weight: bold;border: none;display: flex; flex-wrap: nowrap; align-items: center; gap: 5px;">Admisión
                         <svg style="transform: rotate(90deg);" xmlns="http://www.w3.org/2000/svg" width="6" height="6" fill="currentColor" class="bi bi-triangle-fill" viewBox="0 0 16 16">
                        <path fill-rule="evenodd" d="M7.022 1.566a1.13 1.13 0 0 1 1.96 0l6.857 11.667c.457.778-.092 1.767-.98 1.767H1.144c-.889 0-1.437-.99-.98-1.767z"/>
                      </svg></button>
                </div>
            </div>
        </div>
    </nav>
    {% block content %}
    {% endblock %}
</body>
    </html>